approvals:
  # PR needs at least 1 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:+1:|👍)$"
  #ignore: none
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:-1:|👎)$"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a public zalando org member
      # (any org in here counts)
      - logistics
    # OR a collaborator of the repo
    collaborators: true
    # OR one of these guys
    users:
      # - lfischer
      # - prayerslayer
      # - mfellner
  # you can define groups from which you
  # require approvals
  #groups:
    # this defines a "zalando" approver group
    #zalando:
      # where the approval check will fail if there
      # is less than 1 approval from it
 #     minimum: 1
      # the group includes every public zalando org member
 #     from:
 #       orgs:
 #         - ale
commit:
  message:
    # note that there are no default patterns for commit messages
    patterns:
      - "#[0-9]+"
      - "ALE-[0-9]+"
      - "ZALOS-[0-9]+"
autobranch:
  # things in curly brackets are variables that
  # will be replaced. possible variables:
  # - number: the issue number
  # - title: the issue title
  # - labels: the labels of the issue at opening time
  pattern: "feature/{number}-{title}"
  # restrict branch name to maximum this many characters
  length: 70
# team should be valid team id in team service https://teams.auth.zalando.com/api/teams/:id
X-Zalando-Team: "ale"
# type should be one of [code, doc, config, tools, secrets]
# code will be the default value, if X-Zalando-Type is not found in .zappr.yml
X-Zalando-Type: doc
